### ISSUE TITLE
EBB SB2209/2240 version

### ISSUE THREAD

**Issue by sprior** [rongith/Stealthburner_LGX_Mount#1]
I've got an LGX and just got an EBB SB2240 toolhead board and it looks like some changes would be needed to use your design.  I'm still investigating what might need to change but thought I'd mention it in case others would need the same.

**Comment by rongith** [comment]
Due to the optimized design of those parts for the CW2, there is no room to fit it along an LGX.
![image](https://user-images.githubusercontent.com/7966342/229069334-f70ab694-7d37-46ba-b10b-6af3ff00a908.png)
The LGX is too wide compared to the CW2.
You would need to expend the SB fan body part too to mount the PCB on the right side properly.

**Comment by sprior** [comment]
Ok thanks, I didn't find any info on this before I bought the board so I guess I'll return it.  This issue can serve as some documentation that it won't work without other significant changes.

**Comment by rongith** [comment]
I just imported the BTT models in my CAD after you asked. I add suspicions because I already imported the 2 parts PCB for afterburner. It is a confirmation. I had very few informal requests about that before but I delayed the check. As you, I just wanted it because in the meantime I will switch to CAN wiring. We will have to find an other solution then.

**Comment by sprior** [comment]
I was previously using an EBB42 with my LGX and Afterburner.  I was tempted by the SB2240's wiring, but I guess it's back to the EBB42.

**Comment by rongith** [comment]
I'm working on that.
![20240903_160309](https://github.com/user-attachments/assets/b5b61597-e535-4f27-9156-4ea1f64410cc)
